pub mod logger;
pub mod plugin;
pub use plugin::{PluginType, registry::PluginRegistry};
pub mod adapter;
pub mod error;
pub use adapter::registry::AdapterRegistry;
pub mod bot;
pub mod library;
mod utils;
mod version;
pub use version::VERSION;
