[package]
name = "puniyu"
version = "0.1.0"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
tokio.workspace = true

puniyu_core = { path = "../puniyu_core" }
puniyu_plugin_test = { path = "../puniyu_plugins/puniyu_plugin_test", default-features = false }



[[bin]]
name = "puniyu"
path = "src/main.rs"

[features]
preview = ["puniyu_core/core_preview"]