[package]
name = "puniyu"
version = "0.3.0"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
tokio.workspace = true
puniyu_core = { path = "../puniyu_core" }
puniyu_adapter_console = { path = "../adapters/puniyu_adapter_console" }



[[bin]]
name = "puniyu"
path = "src/main.rs"

[features]
preview = ["puniyu_core/core_preview"]
