[package]
name = "puniyu_event_matcher"
version = "0.1.0"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
puniyu_logger.workspace = true

puniyu_element = { path = "../puniyu_element" }
puniyu_event_message = { path = "../puniyu_event_message" }
puniyu_event_core = { path = "../puniyu_event_core" }
puniyu_event_utils = { path = "../puniyu_event_utils" }