[package]
name = "puniyu_element"
version = "0.1.0"
description = "puniyu 的消息元素处理库"
readme = "README.md"
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
strum.workspace = true
serde.workspace = true
serde_json.workspace = true
