name: label
on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened


jobs:
  set-lable:
    runs-on: ubuntu-latest
    steps:
      - name: 获取token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 添加标签
        uses: fuxingloh/multi-labeler@v4
        with:
          github-token: ${{ steps.app-token.outputs.token }}

