name: release
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  release:
    if: "!startsWith(github.head_ref, 'release')"
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          fetch-depth: 0

      - name: 获取token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 运行 release-plz
        id: release
        uses: puniyu/release-action@493d4a9830164de9d89a3f665d1aac70948656b3 # main
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_API_TOKEN }}
          
      - name: 运行 release-plz
        if: ${{ steps.release.outputs.releases_created == 'false' }}
        uses: puniyu/release-action@493d4a9830164de9d89a3f665d1aac70948656b3 # main
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_API_TOKEN }}

